# Generated by Django 5.1.5 on 2025-02-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_release_data_movie_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre',
        ),
    ]
